# Generated by Django 2.0.1 on 2018-08-03 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='biggest_hit',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='birth_date',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
