# Generated by Django 2.0.1 on 2018-08-08 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='album',
            new_name='albums',
        ),
    ]
